import { google } from 'googleapis';
import fs from 'fs';
import path from 'path';

/**
 * GMAIL API CONFIGURATION
 * 
 * Replaces unreliable SMTP with official Gmail API via OAuth2.
 * Requires GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN.
 */

const getGmailClient = () => {
    const { GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN } = process.env;

    if (!GMAIL_CLIENT_ID || !GMAIL_CLIENT_SECRET || !GMAIL_REFRESH_TOKEN) {
        throw new Error("Missing Gmail OAuth2 Credentials");
    }

    const oAuth2Client = new google.auth.OAuth2(
        GMAIL_CLIENT_ID,
        GMAIL_CLIENT_SECRET,
        "https://developers.google.com/oauthplayground" // Redirect URL
    );

    oAuth2Client.setCredentials({ refresh_token: GMAIL_REFRESH_TOKEN });

    return google.gmail({ version: 'v1', auth: oAuth2Client });
};

export const emailService = {
    send: async (to: string, attachmentPath: string): Promise<{ success: boolean; message: string }> => {
        console.log("[EMAIL_START] Initiating Gmail API send flow...");

        try {
            // 1. Check Credentials
            if (!process.env.GMAIL_CLIENT_ID) {
                console.warn("[Email] Missing Gmail Credentials. Using MOCK MODE.");
                return { success: true, message: "Email sent successfully (Mock Mode)." };
            }

            // 2. Prepare content
            console.log("[EMAIL_PDF_READY] Reading attachment...");
            const pdfBuffer = fs.readFileSync(attachmentPath);
            const pdfBase64 = pdfBuffer.toString('base64');
            const filename = path.basename(attachmentPath);

            const sender = process.env.GMAIL_SENDER_EMAIL || "me";

            // 3. Construct Raw MIME Message
            const subject = "Your Dubai Travel Itinerary";
            const boundary = "foo_bar_baz";
            const messageParts = [
                `From: "Dubai Travel Planner" <${sender}>`,
                `To: ${to}`,
                `Subject: ${subject}`,
                `MIME-Version: 1.0`,
                `Content-Type: multipart/mixed; boundary="${boundary}"`,
                "",
                `--${boundary}`,
                `Content-Type: text/html; charset="UTF-8"`,
                `Content-Transfer-Encoding: 7bit`,
                "",
                `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #2563eb;">Your Dubai Travel Itinerary</h2>
                    <p>Hello,</p>
                    <p>Thank you for using the Dubai Travel Planner! We've generated your custom itinerary. You can find it attached as a PDF to this email.</p>
                    <p>Have an amazing trip!</p>
                    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #666;">Generated by AI Travel Assistant • Powered by Gmail API</p>
                </div>
                `,
                "",
                `--${boundary}`,
                `Content-Type: application/pdf; name="${filename}"`,
                `Content-Disposition: attachment; filename="${filename}"`,
                `Content-Transfer-Encoding: base64`,
                "",
                pdfBase64,
                "",
                `--${boundary}--`
            ];

            const rawMessage = messageParts.join("\r\n");
            const encodedMessage = Buffer.from(rawMessage)
                .toString('base64')
                .replace(/\+/g, '-')
                .replace(/\//g, '_')
                .replace(/=+$/, '');

            // 4. Send via Gmail API
            console.log("[EMAIL_GMAIL_API_SEND] Sending request to Google...");
            const gmail = getGmailClient();
            const response = await gmail.users.messages.send({
                userId: 'me',
                requestBody: {
                    raw: encodedMessage
                }
            });

            console.log("[EMAIL_SUCCESS] Gmail API Response:", response.data);
            return { success: true, message: "Email sent successfully" };

        } catch (error: any) {
            console.error("[EMAIL_FAILURE] Gmail API Error:", error.message);
            if (error.response) {
                console.error("Details:", error.response.data);
            }
            return { success: false, message: error.message || "Gmail API Failure" };
        }
    }
};
