import { transporter } from './mailConfig';

/**
 * GMAIL SMTP CONFIGURATION
 * 
 * IMPORTANT CONSTRAINTS:
 * 1. Gmail SMTP is not reliable for production delivery from cloud IPs.
 * 2. Silent drops are expected behavior due to Gmail filtering.
 * 3. This setup is acceptable for DEMOS and MVPs only.
 */
export const emailService = {
    send: async (to: string, attachmentPath: string): Promise<{ success: boolean; message: string }> => {
        if (!process.env.EMAIL_USER || !process.env.EMAIL_APP_PASSWORD) {
            console.warn("[Email] Missing Gmail SMTP Configuration. Using MOCK MODE.");
            return { success: true, message: "Email sent successfully (Mock Mode)." };
        }

        try {
            // Branded HTML Content
            const htmlContent = `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #2563eb;">Your Dubai Travel Itinerary</h2>
                    <p>Hello,</p>
                    <p>Thank you for using the Dubai Travel Planner! We've generated your custom itinerary. You can find it attached as a PDF to this email.</p>
                    <p>Have an amazing trip!</p>
                    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #666;">Generated by AI Travel Assistant • Demo Mode</p>
                </div>
            `;

            const mailOptions = {
                from: `"Dubai Travel Planner" <${process.env.EMAIL_USER}>`,
                to,
                subject: "Your Dubai Travel Itinerary",
                html: htmlContent,
                replyTo: process.env.EMAIL_USER,
                attachments: [
                    {
                        filename: 'itinerary.pdf',
                        path: attachmentPath
                    }
                ]
            };

            const info = await transporter.sendMail(mailOptions);

            // LOGGING & STRICT VALIDATION
            const domain = to.split('@')[1];
            console.log("Email response:", {
                recipient: to,
                domain: domain,
                messageId: info.messageId,
                accepted: info.accepted,
                rejected: info.rejected,
                response: info.response
            });

            if (!info.accepted || info.accepted.length === 0) {
                console.error(`[EMAIL] Delivery rejected by Gmail for ${to}`);
                return { success: false, message: 'EMAIL_NOT_ACCEPTED_BY_PROVIDER' };
            }

            return { success: true, message: 'Email sent successfully!' };
        } catch (error: any) {
            console.error(`[EMAIL_JOB] FAILED for ${to}:`, error.message);
            return { success: false, message: error.message || 'EMAIL_PROVIDER_FAILURE' };
        }
    }
};
