import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { Itinerary } from '../types/itinerary';

export async function generatePDF(itinerary: Itinerary): Promise<string> {
    console.log('[PDF] Starting Final Polish PDF generation with Strict Layout Rules');

    return new Promise((resolve, reject) => {
        const fileName = `itinerary-${Date.now()}.pdf`;
        const outputDir = path.join(process.cwd(), 'tmp');

        try {
            if (!fs.existsSync(outputDir)) {
                fs.mkdirSync(outputDir, { recursive: true });
            }

            const filePath = path.join(outputDir, fileName);

            // Create a document with fixed margins
            const doc = new PDFDocument({
                margin: 40,
                size: 'A4',
                bufferPages: false
            });

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // --- STYLING ---
            const colors = {
                primary: '#1e40af', // Deep blue
                text: '#111827',    // Gray 900
                secondary: '#4b5563', // Gray 600
                accent: '#2563eb',   // Bright blue
                divider: '#e5e7eb'   // Light gray
            };

            const drawFooter = () => {
                const bottom = doc.page.height - 30;
                doc.fillColor('#9ca3af')
                    .fontSize(8)
                    .font('Helvetica')
                    .text('Generated by your AI Travel Assistant • Private & Confidential', 40, bottom, { align: 'center', width: 515 });
            };

            const checkPageBreak = (neededHeight: number) => {
                const threshold = doc.page.height - 60; // 60px bottom safety
                if (doc.y + neededHeight > threshold) {
                    drawFooter();
                    doc.addPage();
                    // doc.y is now back at 40 (margin)
                    return true;
                }
                return false;
            };

            // --- MAIN HEADER ---
            doc.fillColor(colors.primary)
                .fontSize(22)
                .font('Helvetica-Bold')
                .text(itinerary.title || 'Your Dubai Journey', { align: 'left' });

            doc.moveDown(0.2);
            doc.fillColor(colors.secondary)
                .fontSize(10)
                .font('Helvetica')
                .text('Created by your AI Travel Assistant', { align: 'left' });

            doc.moveDown(0.8);
            doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor(colors.divider).lineWidth(1).stroke();
            doc.moveDown(1.2);

            // --- CONTENT FLOW ---
            itinerary.days.forEach((day, dayIdx) => {
                // Estimate Day Header Height (~30px)
                checkPageBreak(30);

                // Day Label
                doc.fillColor(colors.primary)
                    .fontSize(16)
                    .font('Helvetica-Bold')
                    .text(`DAY ${day.day || (dayIdx + 1)}`, { underline: true });

                doc.moveDown(0.4); // Compact spacing after day title

                day.blocks.forEach((block: any, blockIdx: number) => {
                    const isMeal = block.type === 'MEAL' || block.mealType;
                    const typeLabel = isMeal ? 'Meal' : 'Attraction';

                    // Estimate Block Height
                    // Title (~15px) + Description (~12px per line) + Spacing (~10px)
                    const descLines = block.description ? Math.ceil(block.description.length / 80) : 1;
                    const estimatedHeight = 15 + (descLines * 12) + 10;

                    checkPageBreak(estimatedHeight);

                    const currentY = doc.y;

                    // Bullet & Title
                    doc.fillColor(colors.text)
                        .fontSize(12)
                        .font('Helvetica-Bold')
                        .text(`• ${block.activity}`, 40, currentY, { continued: true });

                    // Type Badge (Inline)
                    doc.fillColor(isMeal ? '#059669' : colors.accent)
                        .fontSize(9)
                        .font('Helvetica-Bold')
                        .text(`  [${typeLabel.toUpperCase()}]`, { continued: false });

                    doc.moveDown(0.1);

                    // Content: Cuisine or Description
                    doc.fillColor(colors.secondary)
                        .fontSize(10)
                        .font(isMeal ? 'Helvetica-Oblique' : 'Helvetica');

                    if (isMeal && block.cuisine) {
                        doc.text(`  Cuisine: ${block.cuisine}`, 55);
                    } else if (block.description) {
                        doc.text(`  ${block.description}`, 55, doc.y, { width: 480 });
                    }

                    doc.moveDown(0.6); // Compact spacing between items
                });

                // Spacing between days, but not after the last day
                if (dayIdx < itinerary.days.length - 1) {
                    doc.moveDown(1.2);
                }
            });

            // FINAL FOOTER
            drawFooter();

            console.log('[PDF] Ending document stream');
            doc.end();

            stream.on('finish', () => {
                console.log(`[PDF] Success: ${filePath}`);
                resolve(filePath);
            });
            stream.on('error', err => reject(err));

        } catch (err: any) {
            console.error('[PDF] Fatal Error:', err.message);
            reject(err);
        }
    });
}

export const pdfService = {
    generate: generatePDF
};
