import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { Itinerary } from '../types/itinerary';

export async function generatePDF(itinerary: Itinerary): Promise<string> {
    console.log('[PDF] Starting Final Polish PDF generation with Strict Layout Rules');

    return new Promise((resolve, reject) => {
        const fileName = `itinerary-${Date.now()}.pdf`;
        const outputDir = path.join(process.cwd(), 'tmp');

        try {
            if (!fs.existsSync(outputDir)) {
                fs.mkdirSync(outputDir, { recursive: true });
            }

            const filePath = path.join(outputDir, fileName);

            // Create a document with fixed margins
            const doc = new PDFDocument({
                margin: 40,
                size: 'A4',
                bufferPages: false
            });

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // --- STYLING ---
            const colors = {
                primary: '#1e40af', // Deep blue
                text: '#111827',    // Gray 900
                secondary: '#4b5563', // Gray 600
                accent: '#2563eb',   // Bright blue
                divider: '#e5e7eb'   // Light gray
            };

            const drawFooter = () => {
                const bottom = doc.page.height - 30;
                doc.fillColor('#9ca3af')
                    .fontSize(8)
                    .font('Helvetica')
                    .text('Generated by your AI Travel Assistant • Private & Confidential', 40, bottom, { align: 'center', width: 515 });
            };



            // --- MAIN HEADER ---
            doc.fillColor(colors.primary)
                .fontSize(22)
                .font('Helvetica-Bold')
                .text(itinerary.title || 'Your Dubai Journey', { align: 'left' });

            doc.moveDown(0.2);
            doc.fillColor(colors.secondary)
                .fontSize(10)
                .font('Helvetica')
                .text('Created by your AI Travel Assistant', { align: 'left' });

            doc.moveDown(0.8);
            doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor(colors.divider).lineWidth(1).stroke();
            doc.moveDown(1.2);

            // --- CONTENT FLOW ---
            itinerary.days.forEach((day, dayIdx) => {
                // Buffer check for Day Header: Give it some room at bottom
                const bottomMargin = 80;
                if (doc.y > doc.page.height - bottomMargin) {
                    doc.moveDown(2); // PDFKit will auto-add page if it overflows
                }

                // Day Label
                doc.fillColor(colors.primary)
                    .fontSize(16)
                    .font('Helvetica-Bold')
                    .text(`DAY ${day.day || (dayIdx + 1)}`, { underline: true });

                doc.moveDown(0.4);

                // Group Blocks by Time of Day
                const timeGroups: Record<string, any[]> = { 'Morning': [], 'Afternoon': [], 'Evening': [] };

                day.blocks.forEach((b: any) => {
                    if (b.timeOfDay && timeGroups[b.timeOfDay]) {
                        timeGroups[b.timeOfDay].push(b);
                    } else {
                        // Fallback logic if timeOfDay is missing (should verify validation if this happens often)
                        timeGroups['Morning'].push(b);
                    }
                });

                // Render Groups
                ['Morning', 'Afternoon', 'Evening'].forEach((slot) => {
                    const items = timeGroups[slot];
                    if (items.length === 0) return;

                    // Slot Header
                    if (doc.y > doc.page.height - 60) doc.moveDown(1);

                    doc.moveDown(0.5);
                    doc.fillColor(colors.secondary)
                        .fontSize(10)
                        .font('Helvetica-Bold')
                        .text(slot.toUpperCase(), { underline: false });
                    doc.moveDown(0.2);

                    items.forEach((block: any, blockIdx: number) => {
                        const isMeal = block.type === 'MEAL' || block.mealType;
                        const typeLabel = isMeal ? 'Meal' : 'Attraction';

                        // Safety Check
                        if (doc.y > doc.page.height - 60) doc.moveDown(1);

                        // TRAVEL TIME (Render BEFORE item if exists)
                        if (block.travelTime) {
                            doc.fillColor('#6b7280') // Gray 500
                                .fontSize(8)
                                .font('Helvetica-Oblique')
                                .text(`  ↓ ${block.travelTime}`, 55);
                            doc.moveDown(0.2);
                        }

                        const currentY = doc.y;

                        // Bullet & Title
                        doc.fillColor(colors.text)
                            .fontSize(12)
                            .font('Helvetica-Bold')
                            .text(`• ${block.activity}`, 40, currentY, { continued: true });

                        // Type Badge & Duration
                        doc.fillColor(isMeal ? '#059669' : colors.accent)
                            .fontSize(9)
                            .font('Helvetica-Bold')
                            .text(`  [${typeLabel.toUpperCase()}]`, { continued: true });

                        if (block.duration) {
                            doc.fillColor(colors.secondary)
                                .font('Helvetica')
                                .text(` • ${block.duration}`, { continued: false });
                        } else {
                            doc.text('', { continued: false }); // newline
                        }

                        doc.moveDown(0.1);

                        // Content: Cuisine or Description
                        doc.fillColor(colors.secondary)
                            .fontSize(10)
                            .font(isMeal ? 'Helvetica-Oblique' : 'Helvetica');

                        if (isMeal && block.cuisine) {
                            doc.text(`  Cuisine: ${block.cuisine}`, 55);
                        } else if (block.description) {
                            doc.text(`  ${block.description}`, 55, doc.y, { width: 480 });
                        }

                        // Source (Small Footer)
                        if (block.source) {
                            doc.moveDown(0.1);
                            doc.fillColor('#9ca3af')
                                .fontSize(7)
                                .font('Helvetica')
                                .text(`  Source: ${block.source}`, 55);
                        }

                        doc.moveDown(0.6);
                    });
                });

                if (dayIdx < itinerary.days.length - 1) {
                    doc.moveDown(1.2);
                }
            });

            // FINAL FOOTER (ONLY ONCE AT THE VERY END)
            drawFooter();

            console.log('[PDF] Ending document stream');
            doc.end();

            stream.on('finish', () => {
                console.log(`[PDF] Success: ${filePath}`);
                resolve(filePath);
            });
            stream.on('error', err => reject(err));

        } catch (err: any) {
            console.error('[PDF] Fatal Error:', err.message);
            reject(err);
        }
    });
}

export const pdfService = {
    generate: generatePDF
};
